#!/usr/bin/env python3

import os
import re
import sys
import shutil
import subprocess

def main():
    # check if x509dostool is installed
    if shutil.which("x509dostool") is None:
        print("error: x509dostool is not installed.", file=sys.stderr)
        sys.exit(1)

    # define the list of commands
    test_generate_commands = [
        "x509dostool generate -out test.crt test0 -algo ecdsa -name secp256k1 --explicit --compressed",
        "x509dostool generate -out test.crt test1 -m 1023 --balanced --compressed",
        "x509dostool generate -out test.crt test2 -m 1023 -t 65535 --balanced --compressed",
        "x509dostool generate -out test.crt test3 -p 1023 --balanced",
        "x509dostool generate -out test.crt test4 -p 1023 --balanced --compressed",
        "x509dostool generate -out test.crt test5 -emails 3 -sans 3 -ncs 3 -policies 3",
        "x509dostool generate -out test.crt test6 -length 1023",
        "x509dostool generate -out test.crt test7 -length 1023",
        "x509dostool generate -out test.crt test8 -num 3 -sans 1023 -ncs 1023",
        "x509dostool generate -out test.crt test9 -num 3 -policies 3 --mapping",
        "x509dostool generate -out test.crt test10 -num 3 -repeat 3",
    ]

    # check for the --verbose flag
    verbose = len(sys.argv) > 1 and sys.argv[1] == "--verbose"
    if verbose:
        print("verbose mode enabled.")

    # initialize counters for statistics
    total_count = 0
    success_count = 0
    failure_count = 0

    # loop through each command in the list
    for cmd in test_generate_commands:
        total_count += 1
        # extract test name (match 'test' followed by digits)
        test_name_match = re.search(r'test[0-9]+', cmd)
        test_name = test_name_match.group(0) if test_name_match else ""

        # always output the command in the screen, regardless of verbose
        print(f"\033[32mrunning\033[0m: {cmd}")

        # execute the command to generate the certificate
        if verbose:
            result = subprocess.run(cmd, shell=True, capture_output=False)
        else:
            result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
            output = result.stdout + result.stderr

        # check if the command executed successfully
        if result.returncode != 0:
            failure_count += 1
            print(f"error: command failed: {cmd}\n")
            continue

        # check if the certificate was successfully generated
        if not os.path.isfile("test.crt"):
            failure_count += 1
            print(f"error: certificate not generated by command: {cmd}\n")
            continue

        # check if it's test6 and handle the special case
        if "test6" in cmd:
            # attempt to parse the generated certificate with openssl asn1parse
            print("parsing the certificate generated by test6 with openssl asn1parse...")
            parse_result = subprocess.run(
                ["openssl", "asn1parse", "-in", "test.crt"],
                capture_output=True, text=True
            )
            parse_output = parse_result.stdout + parse_result.stderr

            # check if the output contains "header too long"
            if "header too long" in parse_output:
                success_count += 1
                print("successfully parsed the certificate generated by test6 (header too long is expected)")
            else:
                print("error: failed to parse the certificate generated by test6")
                failure_count += 1

            # output the parse result in verbose mode
            if verbose:
                print(parse_output)
        else:
            # try to parse the generated certificate with openssl asn1parse for other tests
            print("parsing the certificate with openssl asn1parse...")
            parse_result = subprocess.run(
                ["openssl", "asn1parse", "-in", "test.crt"],
                capture_output=True, text=True
            )
            parse_output = parse_result.stdout + parse_result.stderr

            if parse_result.returncode == 0:
                success_count += 1
                print(f"successfully parsed the certificate generated by {test_name}")
            else:
                failure_count += 1
                print(f"error: failed to parse the certificate generated by {test_name}")

            # output the parse result in verbose mode
            if verbose:
                print(parse_output)

        # add a newline after each test command (for readability)
        print("")

        # optional: clean up the generated certificate for the next test
        if os.path.isfile("test.crt"):
            os.remove("test.crt")

    # output the final statistics
    print("-----")
    print(f"total commands: {total_count}")
    print(f"successful commands: {success_count}")
    print(f"failed commands: {failure_count}")

    # check if all tests passed
    if failure_count == 0:
        print("all tests passed")
    else:
        print("some tests failed")

if __name__ == "__main__":
    main()
